apiVersion: apps/v1
kind: Deployment
metadata:
    name: ${ORG_NAME}-${ORG_NODE}
spec:
    selector:
        matchLabels:
            name: ${ORG_NAME}-${ORG_NODE}
    replicas: 1
    template:
        metadata:
            labels:
                name: ${ORG_NAME}-${ORG_NODE}
        spec:
           volumes:
             - name: fabricfiles
               persistentVolumeClaim:
                  claimName: common-pvc
           containers:
             - image: hyperledger/fabric-orderer:2.3
               name: ${ORG_NAME}
               imagePullPolicy: IfNotPresent
               env:
                - name: CONFIGTX_ORDERER_ADDRESSES
                  value: ${ORG_NAME}-${ORG_NODE}:7050
                - name: ORDERER_GENERAL_LISTENADDRESS
                  value: 0.0.0.0
                - name: ORDERER_GENERAL_LISTENPORT
                  value: "7050"
                - name: ORDERER_GENERAL_LOGLEVEL
                  value: debug
                - name: ORDERER_GENERAL_LOCALMSPDIR
                  value: /orgs/ord-orgs/${ORG_NAME}/nodes/${ORG_NODE}.${ORG_DOMAIN}/msp
                - name: ORDERER_GENERAL_LOCALMSPID
                  value: ${ORG_NAME}MSP
                - name: ORDERER_GENERAL_BOOTSTRAPMETHOD
                  value: none
                - name: ORDERER_GENERAL_TLS_ENABLED
                  value: "true"
                - name: ORDERER_GENERAL_TLS_PRIVATEKEY
                  value: /orgs/ord-orgs/${ORG_NAME}/nodes/${ORG_NODE}.${ORG_DOMAIN}/tls/server.key
                - name: ORDERER_GENERAL_TLS_CERTIFICATE
                  value: /orgs/ord-orgs/${ORG_NAME}/nodes/${ORG_NODE}.${ORG_DOMAIN}/tls/server.crt
                - name: ORDERER_GENERAL_TLS_ROOTCAS
                  value: /orgs/ord-orgs/${ORG_NAME}/nodes/${ORG_NODE}.${ORG_DOMAIN}/tls/ca.crt
                - name:  ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
                  value: /orgs/ord-orgs/${ORG_NAME}/nodes/${ORG_NODE}.${ORG_DOMAIN}/tls/server.key
                - name:  ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
                  value: /orgs/ord-orgs/${ORG_NAME}/nodes/${ORG_NODE}.${ORG_DOMAIN}/tls/server.crt

                - name: ORDERER_CONSENSUS_WALDIR
                  value: /var/hyperledger/fabric/data/orderer3/etcdraft/wal
                - name: ORDERER_CONSENSUS_SNAPDIR
                  value: /var/hyperledger/fabric/data/orderer3/etcdraft/wal

                - name: ORDERER_CHANNELPARTICIPATION_ENABLED
                  value: "true"
                - name: ORDERER_MAXREQUESTBODYSIZE
                  value: "1 MB"

                - name: ORDERER_ADMIN_TLS_ENABLED
                  value: "true"
                - name: ORDERER_ADMIN_TLS_CERTIFICATE
                  value: /orgs/ord-orgs/${ORG_NAME}/nodes/${ORG_NODE}.${ORG_DOMAIN}/tls/server.crt
                - name: ORDERER_ADMIN_TLS_ROOTCAS
                  value: /orgs/ord-orgs/${ORG_NAME}/nodes/${ORG_NODE}.${ORG_DOMAIN}/tls/ca.crt
                - name: ORDERER_ADMIN_TLS_PRIVATEKEY
                  value: /orgs/ord-orgs/${ORG_NAME}/nodes/${ORG_NODE}.${ORG_DOMAIN}/tls/server.key

                - name: ORDERER_ADMIN_TLS_CLIENTROOTCAS
                  value: /orgs/ord-orgs/${ORG_NAME}/nodes/${ORG_NODE}.${ORG_DOMAIN}/tls/ca.crt

                - name: ORDERER_OPERATIONS_LISTENADDRESS
                  value: 0.0.0.0:8443
                - name: ORDERER_ADMIN_LISTENADDRESS
                  value: 0.0.0.0:9443

               resources:
                 limits:
                    memory: "250Mi"
                    cpu: "250m"
                 requests:
                    memory: "200Mi"
                    cpu: "150m"               
               
               volumeMounts:
                - name:  fabricfiles
                  mountPath: /orgs
                  subPath: orgs
          
                - name: fabricfiles
                  mountPath: /system-genesis-block
                  subPath: system-genesis-block
