version: '3.9'

networks:
  central_perk:
    name: fabric_test
    #external: true

services:
  keycloak:
    container_name: "ticken.keycloak"
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: "start-dev"
    networks:
      - central_perk
    volumes:
      - ./themes:/opt/keycloak/themes
