apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${ORG_NAME}-${ORG_NODE}-tls-cert
spec:
  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - localhost
    - ${ORG_NAME}-${ORG_NODE}
    - ${ORG_NAME}-${ORG_NODE}.${CLUSTER_NAMESPACE}.svc.cluster.local
    - ${ORG_NAME}-${ORG_NODE}.${DOMAIN}
    - ${ORG_NAME}-${ORG_NODE}-operations.${DOMAIN}
  ipAddresses:
    - 127.0.0.1
  secretName: ${ORG_NAME}-${ORG_NODE}-tls-cert
  issuerRef:
    name: ${ORG_NAME}-tls-cert-issuer
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${ORG_NAME}-${ORG_NODE}
spec:
  selector:
    matchLabels:
      name: ${ORG_NAME}-${ORG_NODE}
  replicas: 1
  template:
    metadata:
      labels:
        name: ${ORG_NAME}-${ORG_NODE}
    spec:
      volumes:
        - name: fabric-files
          persistentVolumeClaim:
            claimName: common-pvc

        - name: fabric-config
          configMap:
            name: ${ORG_NAME}-config

        - name: tls-cert-volume
          secret:
            secretName: ${ORG_NAME}-${ORG_NODE}-tls-cert
      containers:
        - name: peer
          image: ${FABRIC_PEER_IMAGE}
          env:
            - name: FABRIC_CFG_PATH
              value: /var/hyperledger/fabric/config

            - name: CORE_PEER_ID
              value: ${ORG_NAME}-${ORG_NODE}

            - name: CORE_PEER_ADDRESS
              value: ${ORG_NAME}-${ORG_NODE}:7051

            - name: CORE_PEER_CHAINCODEADDRESS
              value: ${ORG_NAME}-${ORG_NODE}:7052

            - name: CORE_PEER_CHAINCODELISTENADDRESS
              value: 0.0.0.0:7052

            - name: CORE_PEER_LOCALMSPID
              value: ${ORG_NAME}MSP

            - name: CORE_PEER_TLS_ENABLED
              value: "true"

            - name: CORE_PEER_TLS_CERT_FILE
              value: /var/hyperledger/fabric/config/tls/tls.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /var/hyperledger/fabric/config/tls/tls.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /var/hyperledger/fabric/config/tls/ca.crt

            - name: CORE_OPERATIONS_TLS_CERT_FILE
              value: /var/hyperledger/fabric/config/tls/tls.crt
            - name: CORE_OPERATIONS_TLS_KEY_FILE
              value: /var/hyperledger/fabric/config/tls/tls.key
            - name: CORE_OPERATIONS_TLS_ROOTCERT_FILE
              value: /var/hyperledger/fabric/config/tls/ca.crt

            - name: CORE_PEER_MSPCONFIGPATH
              value: /orgs/peer-orgs/${ORG_NAME}/nodes/${ORG_NAME}-${ORG_NODE}/msp

            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: "CouchDB"
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
              value: "localhost:5984"
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
              value: admin
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
              value: adminpw

          ports:
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 8443

          volumeMounts:
            - name: fabric-files
              mountPath: /orgs
              subPath: orgs

            - name: fabric-config
              mountPath: /var/hyperledger/fabric/config

            - name: tls-cert-volume
              mountPath: /var/hyperledger/fabric/config/tls
              readOnly: true

        - name: couchdb
          image: ${COUCHDB_IMAGE}
          env:
            - name: COUCHDB_USER
              value: admin
            - name: COUCHDB_PASSWORD
              value: adminpw
          ports:
            - containerPort: 5984