apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${ORG_NAME}-${ORG_NODE}
spec:
  selector:
    matchLabels:
      name: ${ORG_NAME}-${ORG_NODE}
  replicas: 1
  template:
    metadata:
      labels:
        name: ${ORG_NAME}-${ORG_NODE}
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: common-pvc

        - name: builders-config
          configMap:
            name: ${ORG_NAME}-peers-config
            items:
              - key: core.yaml
                path: core.yaml
        - name: external-builder-detect
          configMap:
            name: ${ORG_NAME}-peers-config
            items:
              - key: detect
                path: detect
                mode: 0544
        - name: external-builder-build
          configMap:
            name: ${ORG_NAME}-peers-config
            items:
              - key: build
                path: build
                mode: 0544
        - name: external-builder-release
          configMap:
            name: ${ORG_NAME}-peers-config
            items:
              - key: release
                path: release
                mode: 0544
      containers:
        - name: peer
          image: hyperledger/fabric-peer:2.3
          command: [ "sh", "-c", "peer node start" ]
          env:
            - name: CORE_PEER_ADDRESSAUTODETECT
              value: "true"
            - name: CORE_PEER_ID
              value: ${ORG_NAME}-${ORG_NODE}
            - name: CORE_PEER_ADDRESS
              value: ${ORG_NAME}-${ORG_NODE}:7051
            - name: CORE_PEER_LISTENADDRESS
              value: 0.0.0.0:7051
            - name: CORE_PEER_EVENTS_ADDRESS
              value: 0.0.0.0:7061
            - name: CORE_PEER_GOSSIP_BOOTSTRAP
              value: ${ORG_NAME}-${ORG_NODE}:7051
            - name: CORE_PEER_GOSSIP_ENDPOINT
              value: ${ORG_NAME}-${ORG_NODE}:7051
            - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
              value: ${ORG_NAME}-${ORG_NODE}:7051
            - name: CORE_PEER_GOSSIP_ORGLEADER
              value: "false"
            - name: CORE_PEER_GOSSIP_USELEADERELECTION
              value: "true"
            - name: CORE_PEER_PROFILE_ENABLED
              value: "true"
            - name: CORE_PEER_LOCALMSPID
              value: ${ORG_NAME}MSP
            - name: CORE_PEER_MSPCONFIGPATH
              value: /orgs/peer-orgs/${ORG_NAME}/nodes/${ORG_NODE}.${ORG_NAME}/msp
            - name: FABRIC_LOGGING_SPEC
              value: debug
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_CERT_FILE
              value: /orgs/peer-orgs/${ORG_NAME}/nodes/${ORG_NODE}.${ORG_NAME}/tls/server.crt
            - name: CORE_PEER_TLS_KEY_FILE
              value: /orgs/peer-orgs/${ORG_NAME}/nodes/${ORG_NODE}.${ORG_NAME}/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /orgs/peer-orgs/${ORG_NAME}/nodes/${ORG_NODE}.${ORG_NAME}/tls/ca.crt
            - name: CORE_LEDGER_STATE_STATEDATABASE
              value: "CouchDB"
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
              value: "localhost:5984"
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
              value: admin
            - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
              value: adminpw
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric
            - name: CORE_OPERATIONS_LISTENADDRESS
              value: 0.0.0.0:8443
            - name: CORE_METRICS_PROVIDER
              value: prometheus
          ports:
            - containerPort: 7051
            - containerPort: 7052
            - containerPort: 7053
            - containerPort: 8443
          resources:
            limits:
              memory: "300Mi"
              cpu: "300m"
            requests:
              memory: "200Mi"
              cpu: "200m"
          volumeMounts:
            - mountPath: /opt/gopath/src/github.com/chaincode/
              name: fabricfiles
              subPath: chaincode/
            - mountPath: /orgs
              name: fabricfiles
              subPath: orgs
            - mountPath: /var/hyperledger/production
              name: fabricfiles
              subPath: state/${ORG_NAME}/peer0
            - mountPath: /etc/hyperledger/fabric/core.yaml
              name: builders-config
              subPath: core.yaml
            - mountPath: /builders/external/bin/detect
              name: external-builder-detect
              subPath: detect
            - mountPath: /builders/external/bin/build
              name: external-builder-build
              subPath: build
            - mountPath: /builders/external/bin/release
              name: external-builder-release
              subPath: release

        - name: couchdb
          image: couchdb:3.2.2
          env:
            - name: COUCHDB_USER
              value: admin
            - name: COUCHDB_PASSWORD
              value: adminpw
          resources:
            limits:
              memory: "300Mi"
              cpu: "300m"
            requests:
              memory: "200Mi"
              cpu: "200m"
          volumeMounts:
            - mountPath: /opt/couchdb/data
              name: fabricfiles
              subPath: state/${ORG_NAME}/peer0-couchdb
