apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${ORG_NAME}-peer0-cli
spec:
  selector:
    matchLabels:
      name: ${ORG_NAME}-peer0-cli
  template:
    metadata:
      labels:
        name: ${ORG_NAME}-peer0-cli
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: common-pvc

      containers:
        - name: ${ORG_NAME}-peer0-cli
          stdin: true
          tty: true
          resources:
            limits:
              memory: "300Mi"
              cpu: "200m"
            requests:
              memory: "200Mi"
              cpu: "90m"
          image: hyperledger/fabric-tools:2.3
          workingDir: /
          env:
            - name: ORDERER_CA
              value: /orgs/ord-orgs/${ORD_NAME}/msp/tlscacerts/tlsca.${ORD_DOMAIN}-cert.pem
            - name: CORE_PEER_ADDRESS
              value: ${ORG_NAME}-peer0:7051
            - name: CORE_PEER_ID
              value: cli-peer0-${ORG_NAME}
            - name: CORE_PEER_LOCALMSPID
              value: ${ORG_MSP}
            - name: CORE_PEER_MSPCONFIGPATH
              value: /orgs/peer-orgs/${ORG_NAME}/users/Admin@${ORG_DOMAIN}/msp
            - name: CORE_PEER_TLS_CERT_FILE
              value: /orgs/peer-orgs/${ORG_NAME}/nodes/peer0.${ORG_DOMAIN}/tls/server.crt
            - name: CORE_PEER_TLS_ENABLED
              value: "true"
            - name: CORE_PEER_TLS_KEY_FILE
              value: /orgs/peer-orgs/${ORG_NAME}/nodes/peer0.${ORG_DOMAIN}/tls/server.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /orgs/peer-orgs/${ORG_NAME}/nodes/peer0.${ORG_DOMAIN}/tls/ca.crt
            - name: GOPATH
              value: /opt/gopath
            - name: SYS_CHANNEL
              value: system-channel
            - name: CORE_CHAINCODE_BUILDER
              value: hyperledger/fabric-ccenv:1.4.8
            - name: FABRIC_LOGGING_SPEC
              value: DEBUG
          volumeMounts:
            - mountPath: /orgs
              name: fabricfiles
              subPath: orgs
            - mountPath: /configtx
              name: fabricfiles
              subPath: configtx
            - mountPath: /channel-artifacts
              name: fabricfiles
              subPath: channel-artifacts
            - mountPath: /scripts
              name: fabricfiles
              subPath: scripts
            - mountPath: /opt/gopath/src/github.com/chaincode
              name: fabricfiles
              subPath: chaincode
