apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ticken-validator-service
    spec:
      selector:
        matchLabels:
          name: ticken-validator-service

      replicas: 1
      template:
        metadata:
          labels:
            name: ticken-validator-service
        spec:
          volumes:
            - name: service-storage
              persistentVolumeClaim:
                claimName: common-pvc

            - name: service-config
              configMap:
                name: ticken-validator-service-config

          containers:
            - image: ${SERVICE_IMAGE}
              name: ticken-validator-service
              imagePullPolicy: IfNotPresent
              ports:
                - containerPort: 8000
              env:
                - name: ENV
                  value: "stage"
                - name: DB_CONN_STRING
                  value: "mongodb://admin:admin@validator-service-mongodb-clusterip:27017/?authSource=admin"
                - name: BUS_CONN_STRING
                  value: "amqp://user:password@rabbitmq-clusterip:5672/"
                - name: CONFIG_FILE_PATH
                  value: "/"
                - name: CONFIG_FILE_NAME
                  value: "config.json"
                - name: HSM_ENCRYPTION_KEY
                  value: "3s6v9y/B?E(H+MbQeThWmZq4t7w!z%C&"
                - name: TICKEN_WALLET_KEY
                  value: "4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d"
              volumeMounts:
                - name: service-config
                  mountPath: /config.json
                  subPath: config.json

                - name: service-storage
                  mountPath: /storage
                  subPath: ticken-validator-service/app

                - name: service-storage
                  mountPath: /cluster/orgs
                  subPath: orgs


  - apiVersion: v1
    kind: Service
    metadata:
      name: validator-service-clusterip

    spec:
      type: ClusterIP
      selector:
        app: ticken-validator-service

      ports:
        - name: ticken-validator-service
          protocol: TCP
          port: 80
          targetPort: 8000