apiVersion: batch/v1
kind: Job
metadata:
  name: create-channel-${CHANNEL_NAME}
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: create-channel-${CHANNEL_NAME}
    spec:
      volumes:
        - name: fabric-files
          persistentVolumeClaim:
            claimName: common-pvc
      containers:
        - name: generate-certs
          image: ${FABRIC_TOOLS_IMAGE}
          workingDir: /
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "350m"
          volumeMounts:
            - mountPath: /orgs
              name: fabric-files
              subPath: orgs

            - mountPath: /scripts
              name: fabric-files
              subPath: scripts

            - mountPath: /configtx
              name: fabric-files
              subPath: configtx

            - mountPath: /channel-artifacts
              name: fabric-files
              subPath: channel-artifacts
          command:
            - /bin/sh
            - -c
            - ./scripts/channel/create-channel.sh ${CHANNEL_NAME} ${ORDERER_ORG_NAME}
      restartPolicy: Never