apiVersion: batch/v1
kind: Job
metadata:
  name: activate-chaincode-${CHAINCODE_NAME}-${ORG_NAME}
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: create-certs
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: common-pvc
      containers:
        - name: generate-certs
          image: hyperledger/fabric-ca-tools:latest
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "350m"
          volumeMounts:
            - mountPath: /orgs
              name: fabricfiles
              subPath: orgs

            - mountPath: /scripts
              name: fabricfiles
              subPath: scripts
          command:
            - /bin/sh
            - -c
            - |
              ./scripts/activate-chaincode.sh ${ORG_NAME} ${ORG_NODE} ${ORG_DOMAIN} ${CHANNEL_NAME} ${CHAINCODE_ID} ${CHAINCODE_NAME} ${ORDERER_ORG_NAME} ${ORDERER_ORG_DOMAIN}
      restartPolicy: Never
