apiVersion: batch/v1
kind: Job
metadata:
  name: activate-chaincode-${CHAINCODE_NAME}-${ORG_NAME}
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: create-certs
    spec:
      volumes:
        - name: fabricfiles
          persistentVolumeClaim:
            claimName: common-pvc

        - name: external-builder-detect
          configMap:
            name: ${ORG_NAME}-peers-config
            items:
              - key: detect
                path: detect
                mode: 0544
      containers:
        - name: activate-chaincode
          image: ${FABRIC_TOOLS_IMAGE}
          workingDir: /
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "500Mi"
              cpu: "350m"
          volumeMounts:
            - mountPath: /orgs
              name: fabricfiles
              subPath: orgs

            - mountPath: /scripts
              name: fabricfiles
              subPath: scripts

            - mountPath: /chaincodes
              name: fabricfiles
              subPath: chaincodes
          command:
            - /bin/sh
            - -c
            - |
              ./scripts/activate-chaincode.sh ${CHANNEL_NAME} ${ORG_NAME} ${ORG_NODE} ${ORDERER_ORG_NAME} ${CHAINCODE_ID} ${CHAINCODE_NAME}
      restartPolicy: Never
