apiVersion: batch/v1
kind: Job
metadata:
  name: activate-chaincode-${CHAINCODE_NAME}-${ORG_NAME}
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: create-certs
    spec:
      volumes:
        - name: fabric-files
          persistentVolumeClaim:
            claimName: common-pvc

        - name: fabric-config
          configMap:
            name: ${ORG_NAME}-config

      containers:
        - name: activate-chaincode
          image: ${FABRIC_TOOLS_IMAGE}
          workingDir: /

          volumeMounts:
            - mountPath: /orgs
              name: fabric-files
              subPath: orgs

            - mountPath: /scripts
              name: fabric-files
              subPath: scripts

            - mountPath: /chaincodes
              name: fabric-files
              subPath: chaincodes

            - mountPath: /config
              name: fabric-config
          command:
            - /bin/sh
            - -c
            - |
              ./scripts/chaincode/activate-chaincode.sh ${CHANNEL_NAME} ${ORG_NAME} ${ORG_NODE} ${ORDERER_ORG_NAME} ${CHAINCODE_ID} ${CHAINCODE_NAME}
      restartPolicy: Never
