apiVersion: batch/v1
kind: Job
metadata:
  name: enroll-node-admin-${ORG_NAME}-${ORG_NODE}
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: create-certs
    spec:
      volumes:
        - name: fabric-files
          persistentVolumeClaim:
            claimName: common-pvc

        - name: tls-cert-volume
          secret:
            secretName: ${ORG_NAME}-ca-tls-cert
            optional: false

      containers:
        - name: generate-certs
          image: ${FABRIC_CA_TOOLS_IMAGE}
          volumeMounts:
            - mountPath: /orgs
              name: fabric-files
              subPath: orgs

            - mountPath: /scripts
              name: fabric-files
              subPath: scripts

            - name: tls-cert-volume
              mountPath: /tls
              readOnly: true
          command:
            - /bin/sh
            - -c
            - ./scripts/enrollments/enroll-node-admin.sh ${ORG_NAME} ${ORG_TYPE} ${ORG_NODE} ${RCAADMIN_USER}
      restartPolicy: Never
