apiVersion: batch/v1
kind: Job
metadata:
  name: org-join-channel-${CHANNEL_NAME}-${JOINING_ORG_NAME}
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      name: join-channel-${CHANNEL_NAME}-${JOINING_ORG_NAME}
    spec:
      volumes:
        - name: fabric-files
          persistentVolumeClaim:
            claimName: common-pvc

        - name: fabric-config
          configMap:
            name: ${JOINING_ORG_NAME}-config
      containers:
        - name: generate-certs
          image: ${FABRIC_TOOLS_IMAGE}
          workingDir: /

          volumeMounts:
            - mountPath: /orgs
              name: fabric-files
              subPath: orgs

            - mountPath: /scripts
              name: fabric-files
              subPath: scripts

            - mountPath: /channel-artifacts
              name: fabric-files
              subPath: channel-artifacts

            - mountPath: /config
              name: fabric-config
          command:
            - /bin/sh
            - -c
            - ./scripts/channel/org-join-channel.sh ${CHANNEL_NAME} ${JOINING_ORG_NAME} ${GENESIS_ORG_NAME} ${ORDERER_ORG_NAME}
      restartPolicy: Never