apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ${ORG_NAME}-tls-cert-issuer
spec:
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  commonName: ${ORG_NAME}.example.com
  secretName: ${ORG_NAME}-tls-cert-issuer-secret
  issuerRef:
    name: root-tls-cert-issuer
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ${ORG_NAME}-tls-cert-issuer
spec:
  ca:
    secretName: ${ORG_NAME}-tls-cert-issuer-secret




