apiVersion: v1
kind: PersistentVolume
metadata:
  name: ticken-pv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /ticken-pv/

