apiVersion: v1
kind: Service
metadata:
  name: ${ORG_NAME}-${CHAINCODE_NAME}
spec:
  ports:
    - name: chaincode
      port: 9999
      protocol: TCP
  selector:
    app: ${ORG_NAME}-${CHAINCODE_NAME}