apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-attendants-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'

spec:
  rules:
    - host: ticken.com # for testing only
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ticket-service-clusterip
                port:
                  number: 80

          - path: /events
            pathType: Prefix
            backend:
              service:
                name: ticket-service-clusterip
                port:
                  number: 80