apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-organizers-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'

spec:
  rules:
    - host: ticken.organizers.com # for testing only
      http:
        paths:
          - path: /api/e
            pathType: Prefix
            backend:
              service:
                name: event-service-clusterip
                port:
                  number: 80